version: '3.2'
services:
  squad:
    image: "squadtopida/discord-squad-statusbot:latest"
    container_name: discord-status-bot
    environment:
      - TOKEN=TOKEN
      - BM_ID=ID
      - SERVER_IP=IP:Port
      - STATUS_CMD=!server
